name: MyGitHubAction-Basics
env:
  APPLICATION_NAME: "HTML"
  PACKAGE_NAME: "ver-${{ github.sha }}"
on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in testing
        run: echo "Hello World from Testing Job"

      - name: Execute few commands
        run:
          echo "Hello Mess 1"
          echo "Hello Mess 2"
          echo "App name -- ${{ env.APPLICATION_NAME }}"

      - name: List current folder BEFORE
        run:
          ls -la
          
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: List current folder AFTER
        run:
          ls -la
          
  my_deploy:
    runs-on:  ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print Hello Message in deploy
        run: echo "Deploy pckg name is ${{ env.PACKAGE_NAME }}"
